// Keyword maps for resume section detection

export const SECTION_KEYWORDS = {
  work: [
    "experience",
    "work experience",
    "professional experience",
    "employment",
    "employment history",
    "career history",
    "work history",
    "professional background",
    "professional history",
  ],
  education: [
    "education",
    "academic background",
    "academic history",
    "qualifications",
    "educational background",
    "academic credentials",
  ],
  skills: [
    "skills",
    "technical skills",
    "core competencies",
    "competencies",
    "key skills",
    "areas of expertise",
    "expertise",
    "technologies",
    "technical expertise",
    "tools",
    "languages",
    "programming languages",
  ],
  projects: [
    "projects",
    "personal projects",
    "selected projects",
    "key projects",
    "notable projects",
    "portfolio",
    "open source",
    "open source projects",
  ],
  certificates: [
    "certifications",
    "certificates",
    "licenses",
    "professional certifications",
    "credentials",
    "accreditations",
  ],
  summary: [
    "summary",
    "professional summary",
    "objective",
    "career objective",
    "profile",
    "professional profile",
    "about",
    "overview",
    "executive summary",
  ],
  volunteer: [
    "volunteer",
    "volunteering",
    "volunteer experience",
    "community involvement",
    "civic engagement",
  ],
  awards: [
    "awards",
    "honors",
    "achievements",
    "accomplishments",
    "recognition",
    "awards and honors",
  ],
  publications: ["publications", "papers", "research", "presentations", "conferences"],
};

export type SectionType = keyof typeof SECTION_KEYWORDS;
