name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    uses: abijith-suresh/workflows/.github/workflows/release-please.yml@0424bd486ad1c3e0bbb4d206886dec114872eb68 # v0.5.0-rc
    permissions:
      contents: write
      issues: write
      pull-requests: write
    secrets:
      RELEASE_PLEASE_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
